/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RichlistRouteImport } from './routes/richlist'
import { Route as MiningRouteImport } from './routes/mining'
import { Route as MempoolRouteImport } from './routes/mempool'
import { Route as GraphsRouteImport } from './routes/graphs'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MempoolIndexRouteImport } from './routes/mempool.index'
import { Route as TxTxidRouteImport } from './routes/tx.$txid'
import { Route as BlockHashRouteImport } from './routes/block.$hash'
import { Route as AddressAddrRouteImport } from './routes/address.$addr'
import { Route as MempoolBlockIndexRouteImport } from './routes/mempool.block.$index'
import { Route as ApiV1ChainRouteImport } from './routes/api/v1/chain'
import { Route as ApiV1MempoolIndexRouteImport } from './routes/api/v1/mempool.index'
import { Route as ApiV1BlocksIndexRouteImport } from './routes/api/v1/blocks.index'
import { Route as ApiV1TxHashRouteImport } from './routes/api/v1/tx.$hash'
import { Route as ApiV1BlockIdRouteImport } from './routes/api/v1/block.$id'
import { Route as ApiV1AddressAddrRouteImport } from './routes/api/v1/address.$addr'
import { Route as ApiV1BlocksTipHeightRouteImport } from './routes/api/v1/blocks.tip.height'
import { Route as ApiV1BlockIdTxsRouteImport } from './routes/api/v1/block.$id.txs'

const RichlistRoute = RichlistRouteImport.update({
  id: '/richlist',
  path: '/richlist',
  getParentRoute: () => rootRouteImport,
} as any)
const MiningRoute = MiningRouteImport.update({
  id: '/mining',
  path: '/mining',
  getParentRoute: () => rootRouteImport,
} as any)
const MempoolRoute = MempoolRouteImport.update({
  id: '/mempool',
  path: '/mempool',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphsRoute = GraphsRouteImport.update({
  id: '/graphs',
  path: '/graphs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MempoolIndexRoute = MempoolIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MempoolRoute,
} as any)
const TxTxidRoute = TxTxidRouteImport.update({
  id: '/tx/$txid',
  path: '/tx/$txid',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockHashRoute = BlockHashRouteImport.update({
  id: '/block/$hash',
  path: '/block/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressAddrRoute = AddressAddrRouteImport.update({
  id: '/address/$addr',
  path: '/address/$addr',
  getParentRoute: () => rootRouteImport,
} as any)
const MempoolBlockIndexRoute = MempoolBlockIndexRouteImport.update({
  id: '/block/$index',
  path: '/block/$index',
  getParentRoute: () => MempoolRoute,
} as any)
const ApiV1ChainRoute = ApiV1ChainRouteImport.update({
  id: '/api/v1/chain',
  path: '/api/v1/chain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MempoolIndexRoute = ApiV1MempoolIndexRouteImport.update({
  id: '/api/v1/mempool/',
  path: '/api/v1/mempool/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BlocksIndexRoute = ApiV1BlocksIndexRouteImport.update({
  id: '/api/v1/blocks/',
  path: '/api/v1/blocks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TxHashRoute = ApiV1TxHashRouteImport.update({
  id: '/api/v1/tx/$hash',
  path: '/api/v1/tx/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BlockIdRoute = ApiV1BlockIdRouteImport.update({
  id: '/api/v1/block/$id',
  path: '/api/v1/block/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AddressAddrRoute = ApiV1AddressAddrRouteImport.update({
  id: '/api/v1/address/$addr',
  path: '/api/v1/address/$addr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BlocksTipHeightRoute = ApiV1BlocksTipHeightRouteImport.update({
  id: '/api/v1/blocks/tip/height',
  path: '/api/v1/blocks/tip/height',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BlockIdTxsRoute = ApiV1BlockIdTxsRouteImport.update({
  id: '/txs',
  path: '/txs',
  getParentRoute: () => ApiV1BlockIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/blocks': typeof BlocksRoute
  '/docs': typeof DocsRoute
  '/graphs': typeof GraphsRoute
  '/mempool': typeof MempoolRouteWithChildren
  '/mining': typeof MiningRoute
  '/richlist': typeof RichlistRoute
  '/address/$addr': typeof AddressAddrRoute
  '/block/$hash': typeof BlockHashRoute
  '/tx/$txid': typeof TxTxidRoute
  '/mempool/': typeof MempoolIndexRoute
  '/api/v1/chain': typeof ApiV1ChainRoute
  '/mempool/block/$index': typeof MempoolBlockIndexRoute
  '/api/v1/address/$addr': typeof ApiV1AddressAddrRoute
  '/api/v1/block/$id': typeof ApiV1BlockIdRouteWithChildren
  '/api/v1/tx/$hash': typeof ApiV1TxHashRoute
  '/api/v1/blocks/': typeof ApiV1BlocksIndexRoute
  '/api/v1/mempool/': typeof ApiV1MempoolIndexRoute
  '/api/v1/block/$id/txs': typeof ApiV1BlockIdTxsRoute
  '/api/v1/blocks/tip/height': typeof ApiV1BlocksTipHeightRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/blocks': typeof BlocksRoute
  '/docs': typeof DocsRoute
  '/graphs': typeof GraphsRoute
  '/mining': typeof MiningRoute
  '/richlist': typeof RichlistRoute
  '/address/$addr': typeof AddressAddrRoute
  '/block/$hash': typeof BlockHashRoute
  '/tx/$txid': typeof TxTxidRoute
  '/mempool': typeof MempoolIndexRoute
  '/api/v1/chain': typeof ApiV1ChainRoute
  '/mempool/block/$index': typeof MempoolBlockIndexRoute
  '/api/v1/address/$addr': typeof ApiV1AddressAddrRoute
  '/api/v1/block/$id': typeof ApiV1BlockIdRouteWithChildren
  '/api/v1/tx/$hash': typeof ApiV1TxHashRoute
  '/api/v1/blocks': typeof ApiV1BlocksIndexRoute
  '/api/v1/mempool': typeof ApiV1MempoolIndexRoute
  '/api/v1/block/$id/txs': typeof ApiV1BlockIdTxsRoute
  '/api/v1/blocks/tip/height': typeof ApiV1BlocksTipHeightRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/blocks': typeof BlocksRoute
  '/docs': typeof DocsRoute
  '/graphs': typeof GraphsRoute
  '/mempool': typeof MempoolRouteWithChildren
  '/mining': typeof MiningRoute
  '/richlist': typeof RichlistRoute
  '/address/$addr': typeof AddressAddrRoute
  '/block/$hash': typeof BlockHashRoute
  '/tx/$txid': typeof TxTxidRoute
  '/mempool/': typeof MempoolIndexRoute
  '/api/v1/chain': typeof ApiV1ChainRoute
  '/mempool/block/$index': typeof MempoolBlockIndexRoute
  '/api/v1/address/$addr': typeof ApiV1AddressAddrRoute
  '/api/v1/block/$id': typeof ApiV1BlockIdRouteWithChildren
  '/api/v1/tx/$hash': typeof ApiV1TxHashRoute
  '/api/v1/blocks/': typeof ApiV1BlocksIndexRoute
  '/api/v1/mempool/': typeof ApiV1MempoolIndexRoute
  '/api/v1/block/$id/txs': typeof ApiV1BlockIdTxsRoute
  '/api/v1/blocks/tip/height': typeof ApiV1BlocksTipHeightRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/blocks'
    | '/docs'
    | '/graphs'
    | '/mempool'
    | '/mining'
    | '/richlist'
    | '/address/$addr'
    | '/block/$hash'
    | '/tx/$txid'
    | '/mempool/'
    | '/api/v1/chain'
    | '/mempool/block/$index'
    | '/api/v1/address/$addr'
    | '/api/v1/block/$id'
    | '/api/v1/tx/$hash'
    | '/api/v1/blocks/'
    | '/api/v1/mempool/'
    | '/api/v1/block/$id/txs'
    | '/api/v1/blocks/tip/height'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/blocks'
    | '/docs'
    | '/graphs'
    | '/mining'
    | '/richlist'
    | '/address/$addr'
    | '/block/$hash'
    | '/tx/$txid'
    | '/mempool'
    | '/api/v1/chain'
    | '/mempool/block/$index'
    | '/api/v1/address/$addr'
    | '/api/v1/block/$id'
    | '/api/v1/tx/$hash'
    | '/api/v1/blocks'
    | '/api/v1/mempool'
    | '/api/v1/block/$id/txs'
    | '/api/v1/blocks/tip/height'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/blocks'
    | '/docs'
    | '/graphs'
    | '/mempool'
    | '/mining'
    | '/richlist'
    | '/address/$addr'
    | '/block/$hash'
    | '/tx/$txid'
    | '/mempool/'
    | '/api/v1/chain'
    | '/mempool/block/$index'
    | '/api/v1/address/$addr'
    | '/api/v1/block/$id'
    | '/api/v1/tx/$hash'
    | '/api/v1/blocks/'
    | '/api/v1/mempool/'
    | '/api/v1/block/$id/txs'
    | '/api/v1/blocks/tip/height'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  BlocksRoute: typeof BlocksRoute
  DocsRoute: typeof DocsRoute
  GraphsRoute: typeof GraphsRoute
  MempoolRoute: typeof MempoolRouteWithChildren
  MiningRoute: typeof MiningRoute
  RichlistRoute: typeof RichlistRoute
  AddressAddrRoute: typeof AddressAddrRoute
  BlockHashRoute: typeof BlockHashRoute
  TxTxidRoute: typeof TxTxidRoute
  ApiV1ChainRoute: typeof ApiV1ChainRoute
  ApiV1AddressAddrRoute: typeof ApiV1AddressAddrRoute
  ApiV1BlockIdRoute: typeof ApiV1BlockIdRouteWithChildren
  ApiV1TxHashRoute: typeof ApiV1TxHashRoute
  ApiV1BlocksIndexRoute: typeof ApiV1BlocksIndexRoute
  ApiV1MempoolIndexRoute: typeof ApiV1MempoolIndexRoute
  ApiV1BlocksTipHeightRoute: typeof ApiV1BlocksTipHeightRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/richlist': {
      id: '/richlist'
      path: '/richlist'
      fullPath: '/richlist'
      preLoaderRoute: typeof RichlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mining': {
      id: '/mining'
      path: '/mining'
      fullPath: '/mining'
      preLoaderRoute: typeof MiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mempool': {
      id: '/mempool'
      path: '/mempool'
      fullPath: '/mempool'
      preLoaderRoute: typeof MempoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphs': {
      id: '/graphs'
      path: '/graphs'
      fullPath: '/graphs'
      preLoaderRoute: typeof GraphsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mempool/': {
      id: '/mempool/'
      path: '/'
      fullPath: '/mempool/'
      preLoaderRoute: typeof MempoolIndexRouteImport
      parentRoute: typeof MempoolRoute
    }
    '/tx/$txid': {
      id: '/tx/$txid'
      path: '/tx/$txid'
      fullPath: '/tx/$txid'
      preLoaderRoute: typeof TxTxidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/block/$hash': {
      id: '/block/$hash'
      path: '/block/$hash'
      fullPath: '/block/$hash'
      preLoaderRoute: typeof BlockHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address/$addr': {
      id: '/address/$addr'
      path: '/address/$addr'
      fullPath: '/address/$addr'
      preLoaderRoute: typeof AddressAddrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mempool/block/$index': {
      id: '/mempool/block/$index'
      path: '/block/$index'
      fullPath: '/mempool/block/$index'
      preLoaderRoute: typeof MempoolBlockIndexRouteImport
      parentRoute: typeof MempoolRoute
    }
    '/api/v1/chain': {
      id: '/api/v1/chain'
      path: '/api/v1/chain'
      fullPath: '/api/v1/chain'
      preLoaderRoute: typeof ApiV1ChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/mempool/': {
      id: '/api/v1/mempool/'
      path: '/api/v1/mempool'
      fullPath: '/api/v1/mempool/'
      preLoaderRoute: typeof ApiV1MempoolIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/blocks/': {
      id: '/api/v1/blocks/'
      path: '/api/v1/blocks'
      fullPath: '/api/v1/blocks/'
      preLoaderRoute: typeof ApiV1BlocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tx/$hash': {
      id: '/api/v1/tx/$hash'
      path: '/api/v1/tx/$hash'
      fullPath: '/api/v1/tx/$hash'
      preLoaderRoute: typeof ApiV1TxHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/block/$id': {
      id: '/api/v1/block/$id'
      path: '/api/v1/block/$id'
      fullPath: '/api/v1/block/$id'
      preLoaderRoute: typeof ApiV1BlockIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/address/$addr': {
      id: '/api/v1/address/$addr'
      path: '/api/v1/address/$addr'
      fullPath: '/api/v1/address/$addr'
      preLoaderRoute: typeof ApiV1AddressAddrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/blocks/tip/height': {
      id: '/api/v1/blocks/tip/height'
      path: '/api/v1/blocks/tip/height'
      fullPath: '/api/v1/blocks/tip/height'
      preLoaderRoute: typeof ApiV1BlocksTipHeightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/block/$id/txs': {
      id: '/api/v1/block/$id/txs'
      path: '/txs'
      fullPath: '/api/v1/block/$id/txs'
      preLoaderRoute: typeof ApiV1BlockIdTxsRouteImport
      parentRoute: typeof ApiV1BlockIdRoute
    }
  }
}

interface MempoolRouteChildren {
  MempoolIndexRoute: typeof MempoolIndexRoute
  MempoolBlockIndexRoute: typeof MempoolBlockIndexRoute
}

const MempoolRouteChildren: MempoolRouteChildren = {
  MempoolIndexRoute: MempoolIndexRoute,
  MempoolBlockIndexRoute: MempoolBlockIndexRoute,
}

const MempoolRouteWithChildren =
  MempoolRoute._addFileChildren(MempoolRouteChildren)

interface ApiV1BlockIdRouteChildren {
  ApiV1BlockIdTxsRoute: typeof ApiV1BlockIdTxsRoute
}

const ApiV1BlockIdRouteChildren: ApiV1BlockIdRouteChildren = {
  ApiV1BlockIdTxsRoute: ApiV1BlockIdTxsRoute,
}

const ApiV1BlockIdRouteWithChildren = ApiV1BlockIdRoute._addFileChildren(
  ApiV1BlockIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  BlocksRoute: BlocksRoute,
  DocsRoute: DocsRoute,
  GraphsRoute: GraphsRoute,
  MempoolRoute: MempoolRouteWithChildren,
  MiningRoute: MiningRoute,
  RichlistRoute: RichlistRoute,
  AddressAddrRoute: AddressAddrRoute,
  BlockHashRoute: BlockHashRoute,
  TxTxidRoute: TxTxidRoute,
  ApiV1ChainRoute: ApiV1ChainRoute,
  ApiV1AddressAddrRoute: ApiV1AddressAddrRoute,
  ApiV1BlockIdRoute: ApiV1BlockIdRouteWithChildren,
  ApiV1TxHashRoute: ApiV1TxHashRoute,
  ApiV1BlocksIndexRoute: ApiV1BlocksIndexRoute,
  ApiV1MempoolIndexRoute: ApiV1MempoolIndexRoute,
  ApiV1BlocksTipHeightRoute: ApiV1BlocksTipHeightRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
